schema_version: 1

defaults:
  scale: 1.0
  offset: 0.0
  missing:
    strategy: fill_value
    fill_value: -9999.0

products:
  CLDAS-V2.0:
    resolutions:
      "0.0625":
        variables:
          - source_var: TMP
            internal_var: air_temperature
            unit: K
            offset: 273.15
            missing:
              strategy: interpolate

          - source_var: RHU
            internal_var: relative_humidity
            unit: "%"
            missing:
              strategy: fill_value
              fill_value: -9999.0

          - source_var: PRE
            internal_var: precipitation_amount
            unit: m
            scale: 0.001
            missing:
              strategy: fill_value
              fill_value: 0.0

      "0.25":
        variables:
          - source_var: TMP
            internal_var: air_temperature
            unit: K
            offset: 273.15
            missing:
              strategy: interpolate

          - source_var: PSFC
            internal_var: surface_air_pressure
            unit: Pa
            scale: 100.0
            missing:
              strategy: fill_value
              fill_value: -9999.0

  CLDAS-V2.2:
    resolutions:
      "0.0625":
        variables:
          - source_var: U10
            internal_var: eastward_wind_10m
            unit: m s-1
            missing:
              strategy: interpolate

          - source_var: V10
            internal_var: northward_wind_10m
            unit: m s-1
            missing:
              strategy: interpolate

      "0.25":
        variables:
          - source_var: U10
            internal_var: eastward_wind_10m
            unit: m s-1
            missing:
              strategy: interpolate

          - source_var: V10
            internal_var: northward_wind_10m
            unit: m s-1
            missing:
              strategy: interpolate
