level_1:
  intensity: 0.2
  particles: 100
  opacity: 0.2
  speed: 0.2

level_2:
  intensity: 0.4
  particles: 300
  opacity: 0.4
  speed: 0.4

level_3:
  intensity: 0.6
  particles: 600
  opacity: 0.6
  speed: 0.6

level_4:
  intensity: 0.8
  particles: 1000
  opacity: 0.8
  speed: 0.8

level_5:
  intensity: 1.0
  particles: 1500
  opacity: 1.0
  speed: 1.0
