apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-earth-http
  namespace: digital-earth
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: digital-earth-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: example.com
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: digital-earth-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: digital-earth-web
                port:
                  number: 80
